### TODO#12
### Completa los ... de las siguientes peticiones por orden,
### para probar el API con el plugin REST CLIENT de VsCode

### Create user

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Lorena",
  "email": "lorena@comillas.com",
  "role": "USER",
  "password": "Password17"
}


### Login

POST http://localhost:8080/api/users/me/session
Content-Type: application/json

{
  "email": "lorena@comillas.com",
  "password": "Password17"
}


### Login

POST http://localhost:8080/api/users/me/session
Content-Type: application/json

{
  "email": "lorena@comillas.com",
  "password": "Password17"
}

